version: '3.7'

services:
  web:
    hostname: web
    image: web
    build:
      context: .
      args:
        - NPM_TOKEN=${NPM_TOKEN}
    ports:
      - "80:80"
    networks:
       pub-shared-net:

networks:
  pub-shared-net:
    name: pub-shared-net
    external: true