version: '3.7'

services:
  web-stg:
    hostname: web
    image: web-stg
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    environment:
      - FACET_WALLET_PK=${FACET_WALLET_PK}
      - PORT=8080
    build:
      context: .
      args:
      - NPM_TOKEN=${NPM_TOKEN}
      - RPC=${RPC}
      - CHAIN_ID_HEX=${CHAIN_ID_HEX}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - SENTRY_DSN=${SENTRY_DSN}
      - NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
      - NETWORK_NAME=rabbit.stg
      - SUSPEND_WEBSITE=${SUSPEND_WEBSITE}
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      pub-shared-net:

networks:
  pub-shared-net:
    name: pub-shared-net
    external: true