version: '3.7'

services:
  web:
    hostname: web
    image: web
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    environment:
      - FACET_WALLET_PK=${FACET_WALLET_PK}
    build:
      context: .
      args:
        - NPM_TOKEN=${NPM_TOKEN}
    ports:
      - "80:80"
    networks:
       pub-shared-net:

networks:
  pub-shared-net:
    name: pub-shared-net
    external: true