version: "3.7"

services:
  web-stg:
    hostname: web
    image: web-stg
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    environment:
      - PORT=8080
    build:
      context: .
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      pub-shared-net:

networks:
  pub-shared-net:
    name: pub-shared-net
    external: true
