name: Build

on:
  push:
    branches-ignore:
      - "main"

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    env:
      NPM_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      FACET_WALLET_PK: ${{ secrets.FACET_WALLET_PK }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker compose build;