name: Build

on:
  push:
    branches-ignore:
      - "main"

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    env:
      NPM_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      RPC: random.rpc.com:8545
      CHAIN_ID_HEX: 0x888888
      DEPLOYMENT_NETWORK_NAME: 'ethNetwork'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: config npm
        run: mv .npmrc.deploy .npmrc
      - name: Install modules
        run: npm ci
      - name: code quality
        run: npm run lint
      - name: Build
        run: docker compose build;