name: Reusable Workflow for Continues Deployment & Delivery

on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string

jobs:
  reuse_build_and_validate:
    uses: "./.github/workflows/quality-gate.reusable.yml"
    with:
      save-artifacts: true
      artifact-id: release-ready-build
  deploy_sources:
    needs: reuse_build_and_validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download build folder
        uses: actions/download-artifact@v3
        with:
          name: release-ready-build
          path: build
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          # docker and build are two separate folders
          SOURCE: "docker/* build"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /root/${{ inputs.folder }}
          SCRIPT_BEFORE: |
            rm -rf ${{ inputs.folder }}
          SCRIPT_AFTER: |
            ls -al
            echo $RSYNC_STDOUT
