name: CD to Dev ENV

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    env:
      NPM_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      RPC: random.rpc.com:8545
      CHAIN_ID_HEX: 0x888888
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker compose build --no-cache;
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - 
      name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /root/web-dev 
        SCRIPT_BEFORE: |
          rm -rf web-dev
        SCRIPT_AFTER: |
          ls -al
          echo $RSYNC_STDOUT
    - 
      name: Run Docker Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: 
          export NPM_TOKEN=${{ secrets.PERSONAL_GITHUB_TOKEN }} FACET_WALLET_PK=${{ secrets.FACET_WALLET_PK }} SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} SENTRY_DSN=${{ secrets.SENTRY_DSN }} NEXT_PUBLIC_SENTRY_DSN=${{ secrets.SENTRY_DSN }} RPC=${{ secrets.RPC_DEV }} CHAIN_ID_HEX=${{ secrets.CHAIN_ID_HEX_DEV }};
          export SUSPEND_WEBSITE=${{ vars.SUSPEND_WEBSITE }};
          cd /root/web-dev;
          docker compose down;
          docker builder prune -a -f;
          docker image prune -a -f;
          docker compose build --no-cache;
          docker compose up -d