name: Continues Delivery For STG ENV

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  deploy_release:
    uses: "./.github/workflows/release.reusable.yml"
    with:
      folder: web
      composeFile: docker-compose.stage.yml
    secrets:
      serverSshPrivateKey: ${{ secrets.SERVER_SSH_KEY }}
      remoteHost: ${{ secrets.REMOTE_HOST }}
      remoteUser: ${{ secrets.REMOTE_USER }}
