name: Conditnues Delivery For Dev ENV

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy_release:
    uses: "./.github/workflows/release.reusable.yml"
    with:
      folder: web
      
  Rolluout:
    needs: deploy_release
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker Container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script:
            cd /root/web;
            docker compose down;
            docker builder prune -a -f;
            docker image prune -a -f;
            docker compose build --no-cache;
            docker compose up -d
